### ISSUE TITLE
Blister Critters Quickstart page issues

### ISSUE THREAD

**Issue by Wythemars** [stillfleet/stillfleet.github.io#16]
- [x] The BC QSR cover appears blurry. If you need different art, please email Tony and me.
<img width="1365" alt="Blister Critters QSR - blurry image" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/016d1121-136d-43eb-83fa-269258db23ea">

- [x] Bullets need spaces between themselves and the text, so they need to move further left. Text should stay where it is, not move right. Typical bullet spacing is fine, whatever Google Docs/MS Word uses. I think 0.1–0.3 inches is the rule.
<img width="1365" alt="Blister Critters QSR - bullets need space" src="https://github.com/stillfleet/stillfleet.github.io/assets/119684043/6f0b4c27-2457-4868-8ff7-7421e0a901b1">

**Comment by armahillo** [comment]
@Wythemars The cover is blurry because the image height is `500px` and it's being scaled up to `1700px`. I can re-render a higher-res cover but I will need to do this for every product so that they are all the same size (this was an issue previously). 

Too many high-res images are one of the reasons the previous site loaded slowly, so that would be an opportunity cost to consider here. The current filesize (`382x500px`) is 97 kB, and the `1545x2000px` variant is 2.4 MB (~24x as large). 

| Dimensions | filesize | dimension change | filesize change |
| -- | -- | -- | -- |
| 382x500 (current) | 97 kB | - | - |
| 773x1000 | 856 kB | x2 | 8.8x |
| 1545x2000 | 2.4 MB | x4 | 24.7x |

I might be able to do something with srcsets to allow for multiple resolution versions that are then loaded lazily and mitigate the effect on load time. IIRC, time to [FCP (First Contentful Paint)](https://web.dev/articles/fcp) will affect our search engine ranking. If you want, I can look into comparing page load time with the larger image versus the smaller one, this will take some time to investigate though.

**Comment by armahillo** [comment]
OK I have all of the images re-rendered at 3 sizes plus a truncated one for when height needs to be constrained. 
All images now have:

| desc | dimensions | ~filesize |
| -- | -- | -- |
| truncated (title only) | 600w x 250h | 72kB - 268kB |
| Normal | 386w x 500h | 76kB - 300kB |
| 2x | 773w x 1000h |  285kB - 1.3MB |
| 4x | 1545w x 2000h | 729kB - 4.2MB |

I reviewed all the files and confirmed the dimensions and dpi are all the same, and found the extreme ends of the file-size ranges. Higher-detailed images don't compress as well, so the CRB (mostly a field of black) is only 729kB at it's biggest size, while Monkey in the wrench has a lot of texture so it can't compress as well (4.2MB). 

I might be able to try compressing them further, but will need to revisit it.

This change has suddenly caused the larger version of the images to look _slightly_ different even though I have confirmed multiple times that all the images are exactly the same size.  I'm still looking into what happened there, but I've triple-checked that the images that are being loaded are correct -- it does show that the rendered sizes are different but not why. I'll figure it out.

**Comment by armahillo** [comment]
Confirming that the fuzziness has gone away.

![Screenshot 2024-02-15 at 6 56 47 PM](https://github.com/stillfleet/stillfleet.github.io/assets/502363/7013a41b-90cd-4647-bdf4-4a47038adb2d)
