### ISSUE TITLE
Homepage, unitalicize name of company

### ISSUE THREAD

**Issue by Wythemars** [stillfleet/stillfleet.github.io#37]
Please unitalicize "The Stillfleet Studio" in the one line of body copy on the homepage. This was not italicized in the MS. N.B., names of companies are not italicized, only complete works of art (books, movies, journals, magazines, TV shows, movies, plays, etc.).

**Comment by armahillo** [comment]
@Wythemars An FYI since you are now an empowered editor! :) (I'm making the change, so you don't need to do this, it's just an informational note!)

The homepage is found here: `https://github.com/stillfleet/stillfleet.github.io` -> `index.html` (main list)

This is the relevant line:

https://github.com/stillfleet/stillfleet.github.io/blob/11a430508ce2e05b6482cea245c548ed547c21c3/index.html#L16

The [`<em>` ("**em**phasis") tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em) is what applies the italics. To remove these italics, you can remove the tag:

```html
 <p>The Stillfleet Studio makes high-quality, { ... }
```
